name: Check All Links for Errors

on:
    push:
        paths:
        - "source/**"
  
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: MongoCaleb/action_redirect-checker@main
