name: Node.js SDK v12 CI Tests

on:
  pull_request:
    paths:
      - "examples/node/v12/**"

jobs:
  run-jest-tests:
    name: Run Node.js SDK v12 Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: examples/node/v12
        shell: bash
        run: npm install
      - name: Test JavaScript
        shell: bash
        working-directory: examples/node/v12
        run: |
          if npm run test:js 2>&1 | grep q "failed"
          then
            exit 1
          fi
      - name: Test TypeScript
        shell: bash
        working-directory: examples/node/v12
        run: |
          if npm run test:ts 2>&1 | grep q "failed"
          then
            exit 1
          fi